# docker compose up --build

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      # Puerto para la comunicación interna del controlador KRaft
      - "9093:9093"
    environment:
      # Roles: ahora es broker y controller
      KAFKA_PROCESS_ROLES: "broker,controller"
      # ID del nodo. Debe ser único.
      KAFKA_NODE_ID: 1
      # Listeners: Se añade el listener para el controlador
      KAFKA_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092,CONTROLLER://kafka:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Configuración del Quorum de Controladores KRaft
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
    healthcheck:
      test:
        ["CMD", "kafka-topics", "--bootstrap-server", "kafka:29092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 20

  consumer:
    build:
      context: ./consumer
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      KAFKA_BROKER: kafka:29092

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
